### ISSUE TITLE
Error with QGIS3.14

### ISSUE THREAD

**Issue by ntrip6** [mauroalberti/beePen#3]
I'm encountering this error in QGIS3.14 when attempting to start using pencil in an edit session with a new Annotation layer. I tested in geographical projection (epsg 4326) and in State Plane (epsg 6417). Despite the error I am able to create annotation lines layer and export to vector.
2020-09-08T14:17:36     WARNING    warning:C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py:743: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
              mod = _builtin_import(name, globals, locals, fromlist, level)
Second error 
2020-09-08T14:19:26     WARNING    warning:C:/Users/ntrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\beePen\beePen_QWidget.py:209: DeprecationWarning: QgsCoordinateReferenceSystem.toProj4() is deprecated
              return str(project_crs.toProj4())
             
             traceback: File "C:/Users/ntrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\beePen\beePen_QWidget.py", line 236, in create_annotation_layer
              project_crs_osr = self.get_prjcrs_as_proj4str()
              File "C:/Users/ntrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\beePen\beePen_QWidget.py", line 209, in get_prjcrs_as_proj4str
              return str(project_crs.toProj4())

**Comment by mauroalberti** [comment]
It's a deprecation warning. Next days I will look to update to the recommended method, so to eliminate the errors.

**Comment by mauroalberti** [comment]
Should have been fixed with the release 0.2.3, that has yet to be approved - as of 2020-11-06 12:05 - but can be found as released in github

**Comment by mjohenneken** [comment]
The update might have caused issues with QGIS 3.10. I installed 0.2.3 from the official repository.

```
AttributeError: 'QgsCoordinateReferenceSystem' object has no attribute 'toProj' 
Traceback (most recent call last):
  File "C:/Users/Max-Power/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\beePen\beePen_QWidget.py", line 236, in create_annotation_layer
    project_crs_osr = self.get_prjcrs_as_proj4str()
  File "C:/Users/Max-Power/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\beePen\beePen_QWidget.py", line 209, in get_prjcrs_as_proj4str
    return str(project_crs.toProj())
AttributeError: 'QgsCoordinateReferenceSystem' object has no attribute 'toProj'


Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python-Pfad:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/Max-Power/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Max-Power/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Max-Power/AppData/Roaming/QGIS/QGIS3\profiles\default/python
F:/THS-data/datasets/brs-grasslands/qgis
```

**Comment by mauroalberti** [comment]
'QgsCoordinateReferenceSystem' object has attribute 'toProj' since QGIS 3.10.3, according to documentation (https://qgis.org/api/classQgsCoordinateReferenceSystem.html#a13f006c8df360eb47537f3b190ebda26).
Your version appears to be 3.10.1. 
Would it be possible for you to upgrade to at least 3.10.3 and check if the bug is still there?
I have 3.10.4 on Linux without problems.

mauro

**Comment by mauroalberti** [comment]
Another option obviously is to scale back to the previous beePen version, if you cannot upgrade QGIS.

**Comment by mjohenneken** [comment]
I have another install of 3.16.4 and it is working there.

**Comment by mjohenneken** [comment]
I think it is enough to update the min version. As you already did in dbbf149cb11e412fd8573520723f2fc6a46f78cd 👍
